# Generated by Django 4.1.4 on 2022-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UkCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('Funding_Status', models.CharField(blank=True, max_length=80)),
                ('Estimated_Number_of_Employees', models.CharField(blank=True, max_length=30)),
                ('Total_Funding', models.FloatField(blank=True, null=True)),
                ('Estimated_Revenue', models.CharField(blank=True, max_length=80)),
                ('Last_Funding_Date', models.CharField(blank=True, max_length=50)),
                ('Last_Funding_Type', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
