# Generated by Django 4.1.4 on 2022-12-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfile', '0004_alter_ukcompany_total_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ukcompany',
            name='Estimated_Revenue',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ukcompany',
            name='Funding_Status',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ukcompany',
            name='Last_Funding_Date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ukcompany',
            name='Last_Funding_Type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ukcompany',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ukcompany',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ukcompany',
            name='segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
