# Generated by Django 4.1.4 on 2022-12-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfile', '0005_alter_ukcompany_estimated_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ukcompany',
            name='Total_Funding',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
