# Generated by Django 4.1.4 on 2022-12-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfile', '0006_alter_ukcompany_total_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ukcompany',
            name='Total_Funding',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
