# Generated by Django 4.1.4 on 2022-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfile', '0008_alter_ukcompany_total_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='slug',
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SegmentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('name', models.ManyToManyField(to='mainfile.segment')),
            ],
        ),
    ]
