# Generated by Django 4.1.4 on 2022-12-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainfile', '0009_remove_segment_slug_alter_segment_name_segmentfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ukcompany',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfile.segment'),
        ),
        migrations.DeleteModel(
            name='SegmentField',
        ),
    ]
