# Generated by Django 4.1.4 on 2022-12-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfile', '0010_segment_slug_alter_segment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
