# Generated by Django 4.1.4 on 2022-12-13 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainfile', '0011_alter_segment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5d17738b-ba5c-4783-8156-608380be189d'), unique=True),
        ),
    ]
