# Generated by Django 4.1.4 on 2022-12-13 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainfile', '0013_alter_segment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
