# Generated by Django 4.1.4 on 2022-12-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfile', '0014_alter_segment_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ukcompany',
            old_name='Estimated_Number_of_Employees',
            new_name='estimated_number_of_employees',
        ),
        migrations.RenameField(
            model_name='ukcompany',
            old_name='Estimated_Revenue',
            new_name='estimated_revenue',
        ),
        migrations.RenameField(
            model_name='ukcompany',
            old_name='Funding_Status',
            new_name='funding_status',
        ),
        migrations.RenameField(
            model_name='ukcompany',
            old_name='Last_Funding_Date',
            new_name='last_funding_date',
        ),
        migrations.RenameField(
            model_name='ukcompany',
            old_name='Last_Funding_Type',
            new_name='last_funding_type',
        ),
        migrations.RenameField(
            model_name='ukcompany',
            old_name='Total_Funding',
            new_name='total_funding',
        ),
    ]
